server:
  port: 9091

security:
  #  user:
  #    password: user  # 直接登录时的密码
#  ignored: /
#  sessions: never   # session策略
  oauth2:
    #    sso:
    #      loginPath: /login   # 登录路径
    client:
          #      clientId: 89c4bd2d8aaf1a0046bb
          #      clientSecret: 1c3656d02db003b6e4e6e65bc884566634b8e5dc
          #      accessTokenUri: https://github.com/login/oauth/access_token
          #      userAuthorizationUri: https://github.com/login/oauth/authorize
          #      clientAuthenticationScheme: form
      clientId: clientid
      clientSecret: clientSecret
#      accessTokenUri:  https://127.0.0.1:8443/cas/oauth2.0/accessToken
#      userAuthorizationUri: https://127.0.0.1:8443/cas/oauth2.0/authorize
#      clientAuthenticationScheme: form
      scope: read,write
      auto-approve-scopes: '.*'
    resource:
      #      userInfoUri: https://api.github.com/user
      userInfoUri: https://127.0.0.1:8443/cas/oauth2.0/profile
#      preferTokenInfo: false

#logging:
#  level:
#    root: debug


spring:
  application:
    name: cas-oauth2-client1

# 注册中心的地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

#开启feign自带的断熔处理

#当使用oauth2.enabled=true时无法使用hystrix.enabled=true，因为hystrix的处理使用请求方法不在同一个线程中，
# 当oauth2需要获取http.header内部的信息时，无法取得，因此出错
#分别使用hystrix/ oauth2配置，debug调试发现hystrix使用当前http请求线程切换到另一个线程，而使用oauth2时需要在当前http线程中

feign:
#  hystrix:
#    enabled: true
# oauth2
  oauth2:
    enabled: true
