server:
  port: 8082
  servlet:
    context-path: /client1
security:

  oauth2:
    sso:
      loginPath: /login   # 登录路径
    client:
      clientId: clientId
      clientSecret: clientSecret
      accessTokenUri: http://localhost:8081/oauth/token  #请求令牌地址
      userAuthorizationUri: http://localhost:8081/oauth/authorize  #请求认证地址
    resource:
#      jwt:
#        key-uri: http://localhost:8081/oauth/token_key  #解析jwt令牌所需密钥的地址
      user-info-uri: http://localhost:8081/oauth/profile
#spring:
#  thymeleaf:
#    cache: false