spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2?CharacterEncoding=utf-8
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  profiles:
    active: test
#mybatis:
#  mapper-locations: classpath:/mapper/*.xml
#
#logging:
#  level:
#    root: debug


