spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: as1996
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true

person:
  name: test
  id: 1

#    hibernate:
#      ddl-auto: create


server:
  port: 8082