spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: as1996
    url: jdbc:mysql://localhost:3306/oauth2?CharacterEncoding=utf-8

mybatis:
  mapper-locations: classpath:/mapper/*.xml

logging:
  level:
    root: debug

server:
  port: 9876
