server:
  port: 9999

zuul:
  #  sensitive-headers: Cookie,Set-Cookie
#  retryable: true
  routes:
    api-a:
      #      path: /api-a/**
      sensitiveHeaders:
      url: http://127.0.0.1:9091
#      customSensitiveHeaders: true
    api-b:
      url: http://127.0.0.1:9092
      sensitiveHeaders:
#      customSensitiveHeaders: true
  #add-proxy-headers: true
#  ignore-security-headers: false

#proxy:
#  auth:
#    routes:
#      api-a: oauth2
#      api-b: passthru

logging:
  level:
    root: debug

spring:
  application:
    name: cas-oauth2-zuul

# 注册中心的地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/