# 注册中心的地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#开启feign自带的断熔处理
feign:
#  hystrix:
#    enabled: true
  client:
    config:
      default:
        connectTimeout: 500000
        readTimeout: 500000
        loggerLevel: basic
#  oauth2:
#    enabled: true

#Ribbon的负载均衡策略
#ribbon:
#  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#  MaxAutoRetriesNextServer: 0


server:
  port: 8763

spring:
  application:
    name: tm-client-a
  datasource:
    url: jdbc:mysql://192.168.4.17:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: liu
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true

#
#security:
#  oauth2:
#    client:
#      clientId: clientid
#      clientSecret: clientSecret
#      scope: read,write
#      auto-approve-scopes: '.*'
#    resource:
#      userInfoUri: https://dev.yifenganxin.com:9443/cas/oauth2.0/profile

tm-client-a-url: http://localhost:8764
tm-client-c-url: http://localhost:8765
logging:
  level:
    root: debug

tx-lcn:
  client:
    manager-address: 192.168.4.52:9996
#    manager-address: 192.168.4.17:9999